# Generated by Django 4.1 on 2023-09-19 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demandeApp', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='demande',
            name='is_satisfied',
            field=models.BooleanField(default=False),
        ),
    ]
