# Generated by Django 4.1 on 2023-11-24 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demandeApp', '0003_demande_is_satisfied'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lignereponse',
            options={'ordering': ('produit__name',)},
        ),
    ]
