# Generated by Django 4.2.1 on 2023-05-06 01:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('officineApp', '0007_remove_responsableofficine_fullname'),
        ('UserApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilisateur',
            name='telephone',
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='circonscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='circonscription_utilisateur', to='officineApp.circonscription'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='image',
            field=models.ImageField(blank=True, default='media/images/utilisateurs/default.png', max_length=255, null=True, upload_to='media/images/utilisateurs/'),
        ),
    ]
