# Generated by Django 4.2 on 2023-05-02 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('UserApp', '0001_initial'),
        ('officineApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='circonscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agence_employe', to='officineApp.circonscription'),
        ),
    ]
