# Generated by Django 4.2.1 on 2023-05-06 01:19

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0002_remove_utilisateur_telephone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='geometry',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='image',
            field=models.ImageField(blank=True, default='media/images/utilisateurs/default.jpg', max_length=255, null=True, upload_to='media/images/utilisateurs/'),
        ),
    ]
