# Generated by Django 4.2.1 on 2023-05-07 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0004_alter_utilisateur_is_valide'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='geometry_json',
            field=models.TextField(default=''),
        )
    ]
