# Generated by Django 4.2.1 on 2023-05-07 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0005_utilisateur_geometry_json_alter_utilisateur_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='contact',
            field=models.CharField(default='', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
