# Generated by Django 4.1 on 2023-06-29 11:39

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('officineApp', '0015_alter_garde_options'),
        ('produitApp', '0009_produit_cis_produit_forme_produit_voies'),
        ('UserApp', '0009_alter_utilisateur_circonscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='Demande',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('protected', models.BooleanField(default=False)),
                ('status', models.BooleanField(default=False)),
                ('ordonnance', models.ImageField(blank=True, default='media/images/demandes/default.jpg', max_length=255, null=True, upload_to='media/images/demandes/')),
                ('commentaire', models.TextField(default='')),
                ('officine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='officine_demande', to='officineApp.officine')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='utilisateur_demande', to='UserApp.utilisateur')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LigneDemande',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('protected', models.BooleanField(default=False)),
                ('commentaire', models.TextField(default='')),
                ('demande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demande_lignes', to='UserApp.demande')),
                ('is_available', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='status_ligne_demande', to='produitApp.stockstate')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produit_ligne', to='produitApp.produit')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
