# Generated by Django 4.1 on 2023-06-29 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0010_demande_lignedemande'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lignedemande',
            name='is_available',
        ),
        migrations.AddField(
            model_name='lignedemande',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
