# Generated by Django 4.1 on 2023-06-29 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0012_alter_demande_officine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demande',
            name='commentaire',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
