# Generated by Django 4.1 on 2023-06-29 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0014_alter_demande_officine'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lignedemande',
            name='commentaire',
        ),
    ]
