# Generated by Django 4.1 on 2023-06-30 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0017_alter_reponse_demande'),
    ]

    operations = [
        migrations.AddField(
            model_name='demande',
            name='base64',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='image',
            field=models.ImageField(blank=True, default='', max_length=255, null=True, upload_to='media/images/utilisateurs/'),
        ),
    ]
