# Generated by Django 4.1 on 2023-06-30 21:51

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('officineApp', '0016_merge_20230629_1233'),
        ('UserApp', '0018_demande_base64_alter_utilisateur_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demande',
            name='officine',
        ),
        migrations.AlterField(
            model_name='demande',
            name='ordonnance',
            field=models.ImageField(blank=True, default='', max_length=255, null=True, upload_to='media/images/demandes/'),
        ),
        migrations.CreateModel(
            name='OfficineDemande',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('protected', models.BooleanField(default=False)),
                ('status', models.BooleanField(default=False)),
                ('demande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demande_officine', to='UserApp.demande')),
                ('officine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='officine_demande', to='officineApp.officine')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='reponse',
            name='demande',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demande_reponse', to='UserApp.officinedemande'),
        ),
    ]
