# Generated by Django 4.1 on 2023-07-01 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0019_remove_demande_officine_alter_demande_ordonnance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reponse',
            name='read',
            field=models.BooleanField(default=False),
        ),
    ]
