# Generated by Django 4.1 on 2023-07-01 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0020_reponse_read'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reponse',
            name='demande',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='demande_reponse', to='UserApp.officinedemande'),
        ),
    ]
