# Generated by Django 4.1 on 2023-07-27 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0023_lignedemande_quantite'),
    ]

    operations = [
        migrations.AddField(
            model_name='lignereponse',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lignereponse',
            name='quantite',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='reponse',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
