# Generated by Django 4.1 on 2023-07-29 14:46

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('produitApp', '0014_alter_produitinofficine_options_and_more'),
        ('UserApp', '0024_lignereponse_price_lignereponse_quantite_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubsLigneReponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('protected', models.BooleanField(default=False)),
                ('price', models.IntegerField(default=0)),
                ('quantite', models.IntegerField(default=1)),
                ('ligne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes_sub', to='UserApp.lignereponse')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produit_subs_ligne_reponse', to='produitApp.produit')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
