# Generated by Django 4.1 on 2023-08-01 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0025_subslignereponse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lignedemande',
            name='demande',
        ),
        migrations.RemoveField(
            model_name='lignedemande',
            name='produit',
        ),
        migrations.RemoveField(
            model_name='lignereponse',
            name='produit',
        ),
        migrations.RemoveField(
            model_name='lignereponse',
            name='reponse',
        ),
        migrations.RemoveField(
            model_name='officinedemande',
            name='demande',
        ),
        migrations.RemoveField(
            model_name='officinedemande',
            name='officine',
        ),
        migrations.RemoveField(
            model_name='reponse',
            name='demande',
        ),
        migrations.RemoveField(
            model_name='subslignereponse',
            name='ligne',
        ),
        migrations.RemoveField(
            model_name='subslignereponse',
            name='produit',
        ),
        migrations.DeleteModel(
            name='Demande',
        ),
        migrations.DeleteModel(
            name='LigneDemande',
        ),
        migrations.DeleteModel(
            name='LigneReponse',
        ),
        migrations.DeleteModel(
            name='OfficineDemande',
        ),
        migrations.DeleteModel(
            name='Reponse',
        ),
        migrations.DeleteModel(
            name='SubsLigneReponse',
        ),
    ]
