# Generated by Django 4.2.1 on 2023-05-06 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produitApp', '0004_remove_stockstate_etiquette_remove_stockstate_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockstate',
            name='etiquette',
            field=models.CharField(default='', max_length=225),
        ),
        migrations.AddField(
            model_name='stockstate',
            name='name',
            field=models.CharField(default='', max_length=225),
            preserve_default=False,
        ),
    ]
