# Generated by Django 4.2.1 on 2023-05-06 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produitApp', '0005_stockstate_etiquette_stockstate_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockstate',
            name='classe',
            field=models.CharField(default='', max_length=225),
        ),
    ]
