# Generated by Django 4.2.1 on 2023-05-07 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produitApp', '0006_stockstate_classe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='codebarre',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
