# Generated by Django 4.2.1 on 2023-05-28 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produitApp', '0007_alter_produit_codebarre'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produit',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='produitinofficine',
            options={'ordering': ('produit__name', '-stock_state__etiquette')},
        ),
    ]
