# Generated by Django 4.2.1 on 2023-05-30 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produitApp', '0008_alter_produit_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='cis',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='produit',
            name='forme',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='produit',
            name='voies',
            field=models.CharField(default='', max_length=255),
        ),
    ]
