# Generated by Django 4.1 on 2023-06-29 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produitApp', '0010_alter_produit_cis_alter_produit_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='typeproduit',
            options={'ordering': ('name',)},
        ),
    ]
