# Generated by Django 4.1 on 2023-07-21 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produitApp', '0012_produit_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='produitinofficine',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
