# Generated by Django 4.1 on 2023-07-27 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produitApp', '0013_produitinofficine_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produitinofficine',
            options={'ordering': ('produit__name',)},
        ),
        migrations.RemoveField(
            model_name='produitinofficine',
            name='stock_state',
        ),
    ]
