# Generated by Django 4.1 on 2023-11-24 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officineApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='officine',
            name='base64',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
