# Generated by Django 4.1 on 2023-11-24 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('officineApp', '0002_officine_base64'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officine',
            name='circonscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='circonscription_officine', to='officineApp.circonscription'),
        ),
    ]
