# Generated by Django 4.2 on 2023-05-02 22:21

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('officineApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circonscription',
            name='geometry',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, default='POLYGON EMPTY', srid=4326),
        ),
        migrations.AlterField(
            model_name='officine',
            name='geometry',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, default='POINT EMPTY', srid=4326),
        ),
    ]
