# Generated by Django 4.2 on 2023-05-02 22:22

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('officineApp', '0002_alter_circonscription_geometry_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circonscription',
            name='geometry',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, default=None, srid=4326),
        ),
        migrations.AlterField(
            model_name='officine',
            name='geometry',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, default=None, srid=4326),
        ),
    ]
