# Generated by Django 4.2 on 2023-05-02 22:25

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
import django.contrib.gis.geos.polygon
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('officineApp', '0003_alter_circonscription_geometry_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circonscription',
            name='geometry',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, default=django.contrib.gis.geos.polygon.Polygon(((0.0, 0.0), (0.0, 0.0), (0.0, 0.0), (0.0, 0.0))), srid=4326),
        ),
        migrations.AlterField(
            model_name='officine',
            name='geometry',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, default=django.contrib.gis.geos.point.Point(0, 0), srid=4326),
        ),
    ]
