# Generated by Django 4.2.1 on 2023-05-05 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officineApp', '0005_alter_officine_geometry'),
    ]

    operations = [
        migrations.AddField(
            model_name='responsableofficine',
            name='is_never_connected',
            field=models.BooleanField(default=True),
        ),
    ]
