# Generated by Django 4.2.1 on 2023-05-05 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('officineApp', '0006_responsableofficine_is_never_connected'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='responsableofficine',
            name='fullname',
        ),
    ]
