# Generated by Django 4.2.1 on 2023-05-07 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officineApp', '0007_remove_responsableofficine_fullname'),
    ]

    operations = [
        migrations.AddField(
            model_name='circonscription',
            name='geometry_json',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='officine',
            name='geometry_json',
            field=models.TextField(default=''),
        ),
    ]
