# Generated by Django 4.2.1 on 2023-05-10 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officineApp', '0008_circonscription_geometry_json_officine_geometry_json'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officine',
            name='image',
            field=models.ImageField(blank=True, default='', max_length=255, null=True, upload_to='media/images/officines/'),
        ),
        migrations.AlterField(
            model_name='officine',
            name='image2',
            field=models.ImageField(blank=True, default='', max_length=255, null=True, upload_to='media/images/officines/'),
        ),
        migrations.AlterField(
            model_name='officine',
            name='image3',
            field=models.ImageField(blank=True, default='', max_length=255, null=True, upload_to='media/images/officines/'),
        ),
    ]
