# Generated by Django 4.2.1 on 2023-05-11 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officineApp', '0009_alter_officine_image_alter_officine_image2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='circonscription',
            name='xml',
            field=models.TextField(blank=True, default='', max_length=255, null=True),
        ),
    ]
