# Generated by Django 4.2.1 on 2023-05-11 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officineApp', '0011_alter_circonscription_xml'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circonscription',
            name='geometry_json',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
