# Generated by Django 4.2.1 on 2023-05-12 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officineApp', '0012_alter_circonscription_geometry_json'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officine',
            name='geometry_json',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
