# Generated by Django 4.2.1 on 2023-05-28 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('officineApp', '0013_alter_officine_geometry_json'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='circonscription',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='officine',
            options={'ordering': ('name',)},
        ),
    ]
