# Generated by Django 4.1 on 2023-06-17 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('officineApp', '0014_alter_circonscription_options_alter_officine_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='garde',
            options={'ordering': ('-created_at', '-debut')},
        ),
    ]
