# Generated by Django 4.2.1 on 2023-06-10 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officineApp', '0014_alter_circonscription_options_alter_officine_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='responsableofficine',
            name='fullname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='officine',
            name='lat',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='officine',
            name='lon',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='responsableofficine',
            name='contact',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
