# Generated by Django 4.1 on 2023-06-29 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('officineApp', '0015_alter_garde_options'),
        ('officineApp', '0015_responsableofficine_fullname_alter_officine_lat_and_more'),
    ]

    operations = [
    ]
