# Generated by Django 4.1 on 2023-08-08 11:12

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('protected', models.BooleanField(default=False)),
                ('fullname', models.CharField(blank=True, max_length=255, null=True)),
                ('otp', models.CharField(blank=True, max_length=6, null=True)),
                ('contact', models.CharField(max_length=255, unique=True)),
                ('imei', models.CharField(max_length=255)),
                ('is_valide', models.BooleanField(default=False)),
                ('geometry', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('geometry_json', models.TextField(default='')),
                ('image', models.ImageField(blank=True, default='', max_length=255, null=True, upload_to='media/images/utilisateurs/')),
            ],
        ),
    ]
