# Generated by Django 4.1 on 2023-11-24 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('officineApp', '0003_alter_officine_circonscription'),
        ('UserApp', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='circonscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='circonscription_utilisateur', to='officineApp.circonscription'),
        ),
    ]
