# Generated by Django 4.1 on 2023-08-03 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demandeApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rdvlignereponse',
            name='read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rdvlignereponse',
            name='valided_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
