# Generated by Django 4.1 on 2023-08-08 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('officineApp', '0001_initial'),
        ('UserApp', '0002_initial'),
        ('demandeApp', '0001_initial'),
        ('produitApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subslignereponse',
            name='produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produit_subs_ligne_reponse', to='produitApp.produit'),
        ),
        migrations.AddField(
            model_name='reponse',
            name='demande',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demande_reponse', to='demandeApp.officinedemande'),
        ),
        migrations.AddField(
            model_name='rdvlignereponse',
            name='ligne',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rdv_ligne', to='demandeApp.lignereponse'),
        ),
        migrations.AddField(
            model_name='officinedemande',
            name='demande',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demande_officine', to='demandeApp.demande'),
        ),
        migrations.AddField(
            model_name='officinedemande',
            name='officine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='officine_demande', to='officineApp.officine'),
        ),
        migrations.AddField(
            model_name='lignereponse',
            name='produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produit_ligne_reponse', to='produitApp.produit'),
        ),
        migrations.AddField(
            model_name='lignereponse',
            name='reponse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reponse_lignes', to='demandeApp.reponse'),
        ),
        migrations.AddField(
            model_name='lignedemande',
            name='demande',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demande_lignes', to='demandeApp.demande'),
        ),
        migrations.AddField(
            model_name='lignedemande',
            name='produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produit_ligne', to='produitApp.produit'),
        ),
        migrations.AddField(
            model_name='demande',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='utilisateur_demande', to='UserApp.utilisateur'),
        ),
    ]
