# Generated by Django 4.1 on 2023-08-07 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demandeApp', '0002_rdvlignereponse_read_rdvlignereponse_valided_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='officinedemande',
            old_name='status',
            new_name='propagated',
        ),
        migrations.AddField(
            model_name='demande',
            name='is_finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='demande',
            name='lat',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='demande',
            name='lon',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='demande',
            name='propagating',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='officinedemande',
            name='is_valided',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
